### ISSUE TITLE
Possible to do without this module?

### ISSUE THREAD

**Issue by colemanw** [mattwire/webform_civicrm_esign#1]
Interesting concept. I wonder though if it would work without any custom code. Try this:

- Enable webform_civicrm and esign modules
- Add an activity to the webform with 1 attachment field
- Click on the webform tab and edit the attachment component
- Change its widget type to esign

**Comment by mattwire** [comment]
@colemanw Good idea. I've just tried that and it seems the CiviCRM "file" field type doesn't alllow you to change the widget type.

**Comment by colemanw** [comment]
Ah, right. I remember adding that restriction long ago, because I wasn't aware of any other widgets that could produce a file. Try hacking around it & disabling that form rule to test it out.

**Comment by mattwire** [comment]
@colemanw Ok, I tried that but it doesn't seem to get saved as a file.  The esign module outputs a base64 encoded string which I decode in this module before saving as a file, I'm guessing that webform_civicrm would need to be passed the decoded file data in order to save it?

**Comment by colemanw** [comment]
Fair enough. Thanks for contributing this module!
