### ISSUE TITLE
Trouble following instructions

### ISSUE THREAD

**Issue by benasp123** [mattwire/webform_civicrm_esign#3]
Hi, This looks like a great extension. I'm still pretty new to Civi. I'm having trouble following the instructions. 

**In CiviCRM: An activity type with a "File" custom field.**
Does this mean create an activity here: /civicrm/admin/options/activity_type and then add a custom file field?

**On each webform:
A field with name: esign_custom_field, type: hidden, value: custom field name (eg. custom_9).**
Which field? A field from the activity above? If so, i can't change the type to hidden.

**A field with name: esign_activity_type_id, type: hidden, value: activity type id (eg. 70).**
Again, what filed? A text field?

Thanks

**Comment by mattwire** [comment]
> Hi, This looks like a great extension. I'm still pretty new to Civi. I'm having trouble following the instructions.
> 
> **In CiviCRM: An activity type with a "File" custom field.**
> Does this mean create an activity here: /civicrm/admin/options/activity_type and then add a custom file field?

Under Administer->Custom Fields you need to add a custom field group to a specific activity type (that could be existing or a new one that you've created).   In that custom field group add a "File" type custom field.

> 
> **On each webform: A field with name: esign_custom_field, type: hidden, value: custom field name (eg. custom_9).**
> Which field? A field from the activity above? If so, i can't change the type to hidden.

A webform field of type hidden.  It's used as metadata for this extension.

> 
> **A field with name: esign_activity_type_id, type: hidden, value: activity type id (eg. 70).**
> Again, what filed? A text field?

As above - a hidden webform field.
> 
> Thanks

**Comment by mattwire** [comment]
@benasp123 Please re-open if still an issue
